"""Untrained, grounded text pathways for the regional brain model.

The regional names are engineering analogies to distributed biological language
systems, not claims of anatomical accuracy or demonstrated English competence.
An entire instruction is provided *before* its observation episode; a response
is produced *after* that episode. Explicit BrainState carries regional activity
across successive utterances and observation chunks. The text encoder and byte
decoder still restart each utterance; this is not token-by-token text streaming.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from dataclasses import asdict, dataclass

import torch
from torch import Tensor, nn
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

from .model import Brain, BrainState


@dataclass(frozen=True)
class LanguageConfig:
    hidden_size: int = 128
    embedding_size: int = 64
    max_input_bytes: int = 256
    max_output_bytes: int = 128

    def __post_init__(self) -> None:
        for name, value in asdict(self).items():
            if type(value) is not int or value < 1:
                raise ValueError(f"{name} must be a positive integer; got {value!r}")


class ByteCodec:
    """Fixed UTF-8 byte representation with no fitted vocabulary.

    Limits count UTF-8 bytes, not Unicode characters. Invalid generated byte
    sequences raise by default; callers must explicitly request ``errors='replace'``
    for lossy display. Decoding stops at the first EOS and ignores BOS/PAD.
    """

    PAD = 0
    BOS = 1
    EOS = 2
    BYTE_OFFSET = 3
    VOCAB_SIZE = 259

    def __init__(self, max_bytes: int = 256):
        self.max_bytes = self._positive_limit(max_bytes)

    @staticmethod
    def _positive_limit(value: int) -> int:
        if type(value) is not int or value < 1:
            raise ValueError("max_bytes must be a positive integer")
        return value

    def encode(self, text: str, *, max_bytes: int | None = None) -> list[int]:
        if not isinstance(text, str):
            raise ValueError("text must be a string")
        limit = self.max_bytes if max_bytes is None else self._positive_limit(max_bytes)
        raw = text.encode("utf-8", errors="strict")
        if len(raw) > limit:
            raise ValueError(f"Text contains {len(raw)} UTF-8 bytes; limit is {limit}. No truncation was performed.")
        return [self.BOS, *(byte + self.BYTE_OFFSET for byte in raw), self.EOS]

    def batch_encode(
        self, texts: Sequence[str], *, device: torch.device | str | None = None,
        max_bytes: int | None = None,
    ) -> tuple[Tensor, Tensor]:
        if isinstance(texts, (str, bytes)) or not isinstance(texts, Sequence) or not texts:
            raise ValueError("texts must be a nonempty sequence of strings")
        encoded = [self.encode(text, max_bytes=max_bytes) for text in texts]
        lengths = torch.tensor([len(row) for row in encoded], dtype=torch.long, device=device)
        ids = torch.full((len(encoded), max(map(len, encoded))), self.PAD, dtype=torch.long, device=device)
        for index, row in enumerate(encoded):
            ids[index, :len(row)] = torch.tensor(row, dtype=torch.long, device=device)
        return ids, lengths

    def decode(self, ids: Iterable[int] | Tensor, *, errors: str = "strict") -> str:
        if errors not in ("strict", "replace"):
            raise ValueError("errors must be 'strict' or explicitly 'replace'")
        if isinstance(ids, Tensor):
            if ids.ndim != 1 or ids.dtype != torch.long:
                raise ValueError("ids must be a one-dimensional torch.long tensor")
            tokens = ids.detach().cpu().tolist()
        else:
            tokens = list(ids)
        if any(type(token) is not int or not 0 <= token < self.VOCAB_SIZE for token in tokens):
            raise ValueError(f"IDs must be integers in [0, {self.VOCAB_SIZE})")
        raw = bytearray()
        for token in tokens:
            if token == self.EOS:
                break
            if token >= self.BYTE_OFFSET:
                raw.append(token - self.BYTE_OFFSET)
        return raw.decode("utf-8", errors=errors)


class PosteriorTemporal(nn.Module):
    """Causal recurrent text comprehension with padding excluded from state."""

    def __init__(self, config: LanguageConfig):
        super().__init__()
        self.embedding = nn.Embedding(ByteCodec.VOCAB_SIZE, config.embedding_size, padding_idx=ByteCodec.PAD)
        self.recurrent = nn.GRU(config.embedding_size, config.hidden_size, batch_first=True)

    def forward(self, ids: Tensor, lengths: Tensor) -> tuple[Tensor, Tensor]:
        packed = pack_padded_sequence(
            self.embedding(ids), lengths.detach().cpu(), batch_first=True, enforce_sorted=False,
        )
        packed_states, last = self.recurrent(packed)
        states, _ = pad_packed_sequence(packed_states, batch_first=True, total_length=ids.shape[1])
        return states, last[-1]


class SemanticBridge(nn.Module):
    """Neural interfaces between text states and the distributed brain state."""

    def __init__(self, language_hidden: int, brain_hidden: int):
        super().__init__()
        self.to_brain = nn.Sequential(nn.Linear(language_hidden, brain_hidden), nn.LayerNorm(brain_hidden), nn.Tanh())
        self.from_brain = nn.Sequential(nn.Linear(3 * brain_hidden, language_hidden), nn.LayerNorm(language_hidden), nn.Tanh())

    def comprehend(self, final_text_state: Tensor) -> Tensor:
        return self.to_brain(final_text_state)

    def formulate(self, final_brain_states: Tensor) -> Tensor:
        return self.from_brain(final_brain_states)


class InferiorFrontal(nn.Module):
    """Causal next-byte production conditioned on a completed brain episode."""

    def __init__(self, config: LanguageConfig):
        super().__init__()
        self.embedding = nn.Embedding(ByteCodec.VOCAB_SIZE, config.embedding_size, padding_idx=ByteCodec.PAD)
        self.initial_state = nn.Linear(config.hidden_size, config.hidden_size)
        self.recurrent = nn.GRU(config.embedding_size + config.hidden_size, config.hidden_size, batch_first=True)
        self.readout = nn.Linear(config.hidden_size, ByteCodec.VOCAB_SIZE)

    def forward(self, decoder_input_ids: Tensor, context: Tensor) -> Tensor:
        condition = context[:, None, :].expand(-1, decoder_input_ids.shape[1], -1)
        embedded = torch.cat((self.embedding(decoder_input_ids), condition), dim=-1)
        states, _ = self.recurrent(embedded, self.initial_state(context).tanh().unsqueeze(0))
        return self.readout(states)


class LanguageBrain(nn.Module):
    """A brain plus three separate, initially untrained language networks.

    Comprehension reaches the brain through ``language_context``. Production
    reads final prefrontal, parietal, and hippocampal activity exclusively: there
    is no direct instruction-to-decoder bypass. This supports regional lesions.
    Teacher-forcing inputs start with BOS and contain only the *preceding*
    response bytes. Trainers must shift response targets by one and
    ignore PAD in its loss. Logits at padded decoder positions are meaningless.

    ``forward`` starts a fresh independent episode. ``forward_with_state``
    carries caller-owned regional state across utterances without retaining any
    activity on this module. Prior regional context reaches the existing brain
    recurrence; it does not initialize the separate utterance encoder.
    """

    def __init__(self, brain: Brain, config: LanguageConfig | None = None):
        super().__init__()
        if not isinstance(brain, Brain):
            raise ValueError("brain must be a Brain instance")
        if config is not None and not isinstance(config, LanguageConfig):
            raise ValueError("config must be a LanguageConfig instance")
        self.brain = brain
        self.config = config or LanguageConfig()
        self.codec = ByteCodec(self.config.max_input_bytes)
        self.posterior_temporal = PosteriorTemporal(self.config)
        self.inferior_frontal = InferiorFrontal(self.config)
        self.semantic_bridge = SemanticBridge(self.config.hidden_size, brain.config.hidden_size)
        parameter = next(brain.parameters())
        for module in (self.posterior_temporal, self.inferior_frontal, self.semantic_bridge):
            module.to(device=parameter.device, dtype=parameter.dtype)

    def parameter_counts(self) -> dict[str, int]:
        return {
            name: sum(parameter.numel() for parameter in module.parameters())
            for name, module in (
                ("brain", self.brain), ("posterior_temporal", self.posterior_temporal),
                ("inferior_frontal", self.inferior_frontal), ("semantic_bridge", self.semantic_bridge),
            )
        }

    def prepare_inputs(
        self, texts: Sequence[str], *, device: torch.device | str | None = None,
    ) -> tuple[Tensor, Tensor]:
        """Encode instructions without fitting data or updating any parameter."""
        actual_device = next(self.parameters()).device if device is None else device
        return self.codec.batch_encode(texts, device=actual_device)

    def _validate_ids(self, name: str, ids: Tensor, batch: int, maximum_width: int) -> None:
        if not isinstance(ids, Tensor) or ids.ndim != 2 or ids.shape[0] != batch:
            raise ValueError(f"{name} must have shape [batch, sequence]")
        if not 1 <= ids.shape[1] <= maximum_width:
            raise ValueError(f"{name} sequence width must be in [1, {maximum_width}]")
        if ids.dtype != torch.long or ids.device != next(self.parameters()).device:
            raise ValueError(f"{name} must use torch.long on the model device")
        if not ((ids >= 0) & (ids < ByteCodec.VOCAB_SIZE)).all():
            raise ValueError(f"{name} IDs must be in [0, {ByteCodec.VOCAB_SIZE})")
        if not (ids[:, 0] == ByteCodec.BOS).all():
            raise ValueError(f"{name} must start with BOS")

    def _validate_text(self, ids: Tensor, lengths: Tensor, batch: int) -> None:
        self._validate_ids("text_ids", ids, batch, self.config.max_input_bytes + 2)
        if not isinstance(lengths, Tensor) or lengths.shape != (batch,) or lengths.dtype != torch.long:
            raise ValueError("text_lengths must be a torch.long tensor of shape [batch]")
        if lengths.device != ids.device:
            raise ValueError("text_lengths must use the model device")
        if not ((lengths >= 2) & (lengths <= ids.shape[1])).all():
            raise ValueError("text_lengths must include BOS/EOS and fit the text sequence width")
        positions = torch.arange(ids.shape[1], device=ids.device)[None, :]
        interior = (positions > 0) & (positions < lengths[:, None] - 1)
        if not (ids[interior] >= ByteCodec.BYTE_OFFSET).all():
            raise ValueError("text_ids must contain only byte IDs between BOS and EOS")
        if not (ids.gather(1, (lengths - 1)[:, None]) == ByteCodec.EOS).all():
            raise ValueError("text_lengths must end at EOS")
        if not (ids[positions >= lengths[:, None]] == ByteCodec.PAD).all():
            raise ValueError("text_ids must be right-padded with PAD beyond text_lengths")

    def _validate_decoder(self, ids: Tensor, batch: int) -> None:
        self._validate_ids("decoder_input_ids", ids, batch, self.config.max_output_bytes + 1)
        if (ids[:, 1:] == ByteCodec.BOS).any():
            raise ValueError("decoder_input_ids may contain BOS only at the start")
        padding_started = (ids == ByteCodec.PAD).cumsum(dim=1) > 0
        if (padding_started & (ids != ByteCodec.PAD)).any():
            raise ValueError("decoder_input_ids must use contiguous right padding")
        # An EOS may be retained in a shorter padded row from a shifted batch.
        # It cannot be followed by another byte or another EOS.
        after_eos = (ids == ByteCodec.EOS).cumsum(dim=1) - (ids == ByteCodec.EOS).long() > 0
        if (after_eos & (ids != ByteCodec.PAD)).any():
            raise ValueError("Only PAD may follow EOS in decoder_input_ids")

    def forward(
        self, observations: Mapping[str, Tensor], text_ids: Tensor, text_lengths: Tensor,
        decoder_input_ids: Tensor, *, ablate: Iterable[str] = (),
        memory_context: Tensor | None = None,
    ) -> dict[str, Tensor | dict[str, Tensor]]:
        """Evaluate one independent utterance/observation episode with fresh state."""
        outputs, _ = self._forward_episode(
            observations, text_ids, text_lengths, decoder_input_ids,
            ablate=ablate, memory_context=memory_context, return_state=False,
        )
        return outputs

    def forward_with_state(
        self, observations: Mapping[str, Tensor], text_ids: Tensor, text_lengths: Tensor,
        decoder_input_ids: Tensor, state: BrainState | None = None, *,
        ablate: Iterable[str] = (), memory_context: Tensor | None = None,
    ) -> tuple[dict[str, Tensor | dict[str, Tensor]], BrainState]:
        """Continue a conversation's explicit regional state through an utterance.

        The complete utterance must already be known before these observations;
        neither decoder inputs nor response targets enter the recurrent brain.
        Keep batch rows assigned to the same sessions. Repeating the same text
        while splitting observations preserves whole-episode computation. For
        a new turn, pass its text and the preceding turn's returned state.

        State retains its gradient graph until ``state.detached()`` is called.
        Serialize it with ``brain.state_to_dict`` and restore it with
        ``brain.state_from_dict`` alongside the matching language-model weights.
        This API introduces no parameters or changes to existing checkpoints.
        """
        return self._forward_episode(
            observations, text_ids, text_lengths, decoder_input_ids, state,
            ablate=ablate, memory_context=memory_context, return_state=True,
        )

    def _forward_episode(
        self, observations: Mapping[str, Tensor], text_ids: Tensor, text_lengths: Tensor,
        decoder_input_ids: Tensor, state: BrainState | None = None, *,
        ablate: Iterable[str] = (), memory_context: Tensor | None = None,
        return_state: bool,
    ) -> tuple[dict[str, Tensor | dict[str, Tensor]], BrainState | None]:
        batch, time = self.brain._validate_observations(observations)
        self._validate_text(text_ids, text_lengths, batch)
        self._validate_decoder(decoder_input_ids, batch)
        comprehension_states, final_text_state = self.posterior_temporal(text_ids, text_lengths)
        concept_context = self.semantic_bridge.comprehend(final_text_state)
        # The whole instruction is known before t=0; it contains no future
        # observations, target response, or labels from this episode.
        language_context = concept_context[:, None, :].expand(-1, time, -1)
        if return_state:
            outputs, next_state = self.brain.forward_with_state(
                observations, state, ablate=ablate, return_activity=True,
                language_context=language_context, memory_context=memory_context,
            )
        else:
            # Preserve the original nn.Module call boundary and its hooks for
            # independent episodes, including ComputerBrain instrumentation.
            outputs = self.brain(
                observations, ablate=ablate, return_activity=True,
                language_context=language_context, memory_context=memory_context,
            )
            next_state = None
        activity = outputs["region_activity"]
        final_brain_states = torch.cat(
            [activity[name][:, -1] for name in ("prefrontal_cortex", "parietal_association", "hippocampus")],
            dim=-1,
        )
        production_context = self.semantic_bridge.formulate(final_brain_states)
        return {
            **outputs,
            "language_logits": self.inferior_frontal(decoder_input_ids, production_context),
            "concept_context": concept_context,
            "production_context": production_context,
            "comprehension_states": comprehension_states,
        }, next_state
