"""Tests of observation routing, causal control, and generated byte responses."""

import inspect
import unittest
from dataclasses import fields

import torch
from torch.nn import functional as F

from brain_in_computer.computer_use.model import ComputerBrain, ComputerConfig
from brain_in_computer.language import ByteCodec


class ComputerBrainTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.previous_threads = torch.get_num_threads()
        torch.set_num_threads(1)

    @classmethod
    def tearDownClass(cls):
        torch.set_num_threads(cls.previous_threads)

    def setUp(self):
        torch.manual_seed(125)
        self.model = ComputerBrain(ComputerConfig(hidden_size=12, language_hidden_size=16, embedding_size=8, visual_features=12))
        self.pixels = torch.rand(2, 3, 3, 32, 32)
        self.body = torch.rand(2, 3, 4)
        self.prompts = ["click red", "type hi"]
        self.decoder, self.targets = self.model.prepare_reply(["done", "hi"])

    def forward(self, pixels=None, body=None, prompts=None, decoder=None, **kwargs):
        return self.model(
            self.pixels if pixels is None else pixels,
            self.body if body is None else body,
            self.prompts if prompts is None else prompts,
            self.decoder if decoder is None else decoder,
            **kwargs,
        )

    @staticmethod
    def gradient_sum(module):
        gradients = [parameter.grad for parameter in module.parameters() if parameter.grad is not None]
        if any(not torch.isfinite(gradient).all() for gradient in gradients):
            raise AssertionError("Nonfinite gradient")
        return sum(float(gradient.abs().sum()) for gradient in gradients)

    def test_output_and_distinct_parameter_accounting(self):
        output = self.forward()
        self.assertEqual(tuple(output["logits"].shape), (2, 3, 11))
        self.assertEqual(tuple(output["language_logits"].shape), (2, 5, 259))
        self.assertEqual(tuple(output["scene_logits"].shape), (2, 42))
        counts = self.model.parameter_counts()
        self.assertEqual(counts["total"], sum(parameter.numel() for parameter in self.model.parameters()))
        self.assertEqual(counts["total"], sum(counts[name] for name in ("retina", "brain", "posterior_temporal", "inferior_frontal", "semantic_bridge", "scene_readout")))
        self.assertEqual(counts["trainable"], counts["total"])
        self.assertEqual(counts["frozen"], 0)
        self.assertEqual(len(self.model.brain.regions), 13)
        self.assertIs(self.model.brain, self.model.language.brain)
        self.assertFalse(any(name.startswith("brain.") for name in self.model.state_dict()))

    def test_shifted_reply_targets_include_eos_and_ignore_padding(self):
        decoder, targets = self.model.prepare_reply(["", "hi", "caf\u00e9"])
        self.assertTrue((decoder[:, 0] == ByteCodec.BOS).all())
        self.assertEqual(int(targets[0, 0]), ByteCodec.EOS)
        self.assertTrue((targets[0, 1:] == ByteCodec.PAD).all())
        self.assertEqual(int(targets[1, 2]), ByteCodec.EOS)
        for index, reply in enumerate(("", "hi", "caf\u00e9")):
            self.assertEqual(self.model.language.codec.decode(targets[index]), reply)
        self.assertTrue(torch.equal(decoder[:, 1:], targets[:, :-1]))
        with self.assertRaises(ValueError):
            self.model.prepare_reply(["x" * 65])

    def test_action_learning_reaches_comprehension_retina_and_regional_core(self):
        outputs = self.forward()
        F.cross_entropy(outputs["logits"][:, -1], torch.tensor([0, 5])).backward()
        for module in (self.model.retina, self.model.language.posterior_temporal, self.model.language.semantic_bridge,
                       self.model.brain.regions["visual_cortex"], self.model.brain.regions["prefrontal_cortex"],
                       self.model.brain.regions["motor_cortex"]):
            self.assertGreater(self.gradient_sum(module), 0)
        self.assertEqual(self.gradient_sum(self.model.language.inferior_frontal), 0)

    def test_reply_learning_reaches_pixels_comprehension_core_and_production(self):
        output = self.forward()
        F.cross_entropy(output["language_logits"].flatten(0, 1), self.targets.flatten(), ignore_index=ByteCodec.PAD).backward()
        for module in (self.model.retina, self.model.language.posterior_temporal, self.model.language.inferior_frontal,
                       self.model.language.semantic_bridge, self.model.brain.regions["prefrontal_cortex"],
                       self.model.brain.regions["hippocampus"]):
            self.assertGreater(self.gradient_sum(module), 0)

    def test_perceptual_supervision_reaches_retina_and_visual_cortex_without_output_bypass(self):
        output = self.forward()
        F.cross_entropy(output["scene_logits"][:, :4], torch.tensor([0, 1])).backward()
        for module in (self.model.scene_readout, self.model.retina, self.model.brain.regions["visual_cortex"]):
            self.assertGreater(self.gradient_sum(module), 0)
        with torch.no_grad():
            original = self.forward()
            self.model.scene_readout.weight.zero_()
            self.model.scene_readout.bias.fill_(100)
            altered = self.forward()
        self.assertTrue(torch.equal(original["logits"], altered["logits"]))
        self.assertTrue(torch.equal(original["language_logits"], altered["language_logits"]))
        self.assertFalse(torch.equal(original["scene_logits"], altered["scene_logits"]))

    def test_future_screens_and_response_bytes_cannot_change_past_actions(self):
        altered_pixels = self.pixels.clone()
        altered_pixels[:, -1] = 1 - altered_pixels[:, -1]
        altered_decoder = self.decoder.clone()
        altered_decoder[:, 1] += 1
        with torch.no_grad():
            original = self.forward()
            changed_screen = self.forward(pixels=altered_pixels)
            changed_reply = self.forward(decoder=altered_decoder)
        self.assertTrue(torch.equal(original["logits"][:, :-1], changed_screen["logits"][:, :-1]))
        self.assertFalse(torch.equal(original["logits"][:, -1], changed_screen["logits"][:, -1]))
        self.assertTrue(torch.equal(original["logits"], changed_reply["logits"]))
        self.assertTrue(torch.equal(original["language_logits"][:, :1], changed_reply["language_logits"][:, :1]))

    def test_spatial_and_language_cues_reach_actions_and_replies(self):
        first = torch.zeros_like(self.pixels)
        first[:, :, 0, :16, :16] = 1
        second = torch.zeros_like(first)
        second[:, :, 0, 16:, 16:] = 1
        with torch.no_grad():
            left = self.forward(pixels=first)
            right = self.forward(pixels=second)
            different_prompt = self.forward(prompts=["click blue", "type ok"])
            original = self.forward()
            blocked = self.forward(ablate=("temporal_language",))
            blocked_different = self.forward(prompts=["click blue", "type ok"], ablate=("temporal_language",))
        self.assertFalse(torch.equal(left["region_activity"]["visual_cortex"], right["region_activity"]["visual_cortex"]))
        self.assertFalse(torch.equal(left["language_logits"], right["language_logits"]))
        self.assertFalse(torch.equal(original["logits"], different_prompt["logits"]))
        self.assertTrue(torch.equal(blocked["logits"], blocked_different["logits"]))
        self.assertTrue(torch.equal(blocked["language_logits"], blocked_different["language_logits"]))

    def test_only_screen_body_and_prompt_are_observation_inputs(self):
        captured = []
        handle = self.model.brain.register_forward_pre_hook(lambda module, args, kwargs: captured.append((args, kwargs)), with_kwargs=True)
        try:
            self.forward()
        finally:
            handle.remove()
        self.assertEqual(len(captured), 1)
        args, kwargs = captured[0]
        observations = args[0]
        self.assertEqual(set(observations), {"visual", "auditory", "body", "feedback", "tokens"})
        for channel in ("auditory", "feedback", "tokens"):
            self.assertEqual(int(torch.count_nonzero(observations[channel])), 0)
        self.assertTrue(torch.equal(observations["body"], self.body))
        self.assertIn("language_context", kwargs)
        parameters = inspect.signature(ComputerBrain.forward).parameters
        self.assertEqual(set(parameters), {"self", "pixels", "body", "prompts", "decoder_input_ids", "ablate"})

    def force_generation_token(self, token):
        with torch.no_grad():
            readout = self.model.language.inferior_frontal.readout
            readout.weight.zero_()
            readout.bias.fill_(-20)
            readout.bias[ByteCodec.PAD] = 30
            readout.bias[ByteCodec.BOS] = 25
            readout.bias[token] = 20

    def test_autoregressive_response_masks_specials_runs_core_once_and_restores_modes(self):
        self.force_generation_token(ord("h") + ByteCodec.BYTE_OFFSET)
        self.model.train()
        self.model.retina.eval()
        modes = [module.training for module in self.model.modules()]
        calls = []
        handle = self.model.brain.register_forward_hook(lambda *_: calls.append(1))
        try:
            responses = self.model.respond(self.pixels, self.body, self.prompts, max_new_bytes=3)
        finally:
            handle.remove()
        self.assertEqual(responses, ["hhh", "hhh"])
        self.assertEqual(calls, [1])
        self.assertEqual(modes, [module.training for module in self.model.modules()])
        self.assertTrue(all(parameter.grad is None for parameter in self.model.parameters()))
        self.force_generation_token(ByteCodec.EOS)
        self.assertEqual(self.model.respond(self.pixels, self.body, self.prompts), ["", ""])
        self.force_generation_token(255 + ByteCodec.BYTE_OFFSET)
        self.assertEqual(self.model.respond(self.pixels, self.body, self.prompts, max_new_bytes=1), ["\ufffd", "\ufffd"])

    def test_response_restores_modes_after_invalid_ablation(self):
        self.model.train()
        self.model.retina.eval()
        modes = [module.training for module in self.model.modules()]
        with self.assertRaises(ValueError):
            self.model.respond(self.pixels, self.body, self.prompts, ablate=("missing",))
        self.assertEqual(modes, [module.training for module in self.model.modules()])

    def test_history_and_observation_validation(self):
        for invalid_pixels, invalid_body in (
            (self.pixels[:, :0], self.body[:, :0]),
            (F.pad(self.pixels, (0, 0, 0, 0, 0, 0, 0, 1)), F.pad(self.body, (0, 0, 0, 1))),
            (self.pixels.double(), self.body),
            (self.pixels, self.body.double()),
            (self.pixels[:, :, :, :16], self.body),
            (self.pixels, self.body[:, :1]),
            (self.pixels + 1, self.body),
            (self.pixels * float("nan"), self.body),
            (self.pixels, self.body * float("inf")),
        ):
            with self.assertRaises(ValueError):
                self.forward(pixels=invalid_pixels, body=invalid_body)
        for prompts in ("hi", [], ["one"], ["one", None]):
            with self.subTest(prompts=prompts), self.assertRaises(ValueError):
                self.forward(prompts=prompts)
        for limit in (0, True, 65, 1.5):
            with self.subTest(limit=limit), self.assertRaises(ValueError):
                self.model.respond(self.pixels, self.body, self.prompts, max_new_bytes=limit)

    def test_config_and_double_precision_model(self):
        for field in fields(ComputerConfig):
            for invalid in (0, -1, True, 1.5):
                with self.subTest(field=field.name, value=invalid), self.assertRaises(ValueError):
                    ComputerConfig(**{field.name: invalid})
        self.assertEqual(ComputerConfig().max_history, 3)
        output = self.model.double()(self.pixels.double(), self.body.double(), self.prompts, self.decoder)
        self.assertEqual(output["logits"].dtype, torch.float64)
        self.assertEqual(output["language_logits"].dtype, torch.float64)


if __name__ == "__main__":
    unittest.main()
